import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";
import { toast } from "sonner";
import { Plus } from "lucide-react";

interface AddCourseDialogProps {
	universityId: string;
	onCourseAdded?: () => void;
}

export function AddCourseDialog({ universityId, onCourseAdded }: AddCourseDialogProps) {
	const [open, setOpen] = useState(false);
	const [loading, setLoading] = useState(false);
	const [code, setCode] = useState("");
	const [name, setName] = useState("");

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!code || !name) return;

		setLoading(true);
		try {
			// Check if course already exists
			const { data: existing } = await supabase
				.from('Course')
				.select('id')
				.eq('universityId', universityId)
				.eq('code', code)
				.single();

			if (existing) {
				toast.error("A course with this code already exists.");
				setLoading(false);
				return;
			}

			// Insert new course
			// Note: Assuming 'id' is generated by default (gen_random_uuid()) but we are storing it as TEXT in the schema
			// If the schema expects us to provide an ID, we might need a uuid generator.
			// Based on previous interactions, the schema seems to use text IDs but with default gen_random_uuid(), 
			// OR we need to provide it. Let's try letting DB handle it first.
			const { error } = await supabase.from('Course').insert({
				universityId,
				code: code.toUpperCase(),
				name
			});

			if (error) throw error;

			toast.success("Course added successfully!");
			setOpen(false);
			setCode("");
			setName("");
			onCourseAdded?.();
		} catch (error: any) {
			console.error("Error adding course:", error);
			toast.error(error.message || "Failed to add course");
		} finally {
			setLoading(false);
		}
	};

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button variant="outline" size="sm" className="gap-2">
					<Plus className="h-4 w-4" /> Add Course
				</Button>
			</DialogTrigger>
			<DialogContent className="sm:max-w-[425px]">
				<DialogHeader>
					<DialogTitle>Add New Course</DialogTitle>
					<DialogDescription>
						Create a new course for your university.
					</DialogDescription>
				</DialogHeader>
				<form onSubmit={handleSubmit} className="space-y-4 py-4">
					<div className="grid grid-cols-4 items-center gap-4">
						<Label htmlFor="code" className="text-right">Code</Label>
						<Input
							id="code"
							placeholder="CS101"
							className="col-span-3"
							value={code}
							onChange={(e) => setCode(e.target.value)}
							maxLength={10}
							required
						/>
					</div>
					<div className="grid grid-cols-4 items-center gap-4">
						<Label htmlFor="name" className="text-right">Name</Label>
						<Input
							id="name"
							placeholder="Intro to Computer Science"
							className="col-span-3"
							value={name}
							onChange={(e) => setName(e.target.value)}
							required
						/>
					</div>
					<DialogFooter>
						<Button type="submit" disabled={loading}>
							{loading ? "Adding..." : "Add Course"}
						</Button>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	);
}
